### ISSUE TITLE
Make not equals sign larger than equals sign

### ISSUE THREAD

**Issue by jbphet** [phetsims/arithmetic#112]
@ariel-phet has suggested that the not equals sign be a bit larger than the equals sign in order to draw more visual attention to it.

**Comment by jbphet** [comment]
Assigning to @amanda-phet for her comments.  Please assign back to me if we decide to move forward with this feature.

**Comment by amanda-phet** [comment]
With the grimace face and Try Again button popping up I can see why the change to "not equals" is subtle. However, I didn't think the goal was for it to be really pronounced. I thought it was more so that there was not an incorrect mathematical statement sitting on the screen.

**Comment by ariel-phet** [comment]
Looks fine in latest version
