### ISSUE TITLE
User should have to touch the board twice to commit an answer on the "Factor" screen

### ISSUE THREAD

**Issue by jbphet** [phetsims/arithmetic#116]
Using the "Factor" screen is a little tricky on an iPad because you have to touch in exactly the right square to select the right answer.  When used with a mouse, the selected square is much more apparent because the selection updates based on the "hovering" mouse position (which obviously can't be done in a touch environment).  The design team has suggested that the sim behave such that the user must touch the screen twice to submit their answer on this screen, once to select the square, and once to confirm it as their submission.

**Comment by jbphet** [comment]
This was recently interviewed on. Assigning to @amanda-phet, who conducted the interviews, so that she can comment on how this worked and decide whether the issue is resolved.

**Comment by amanda-phet** [comment]
This worked beautifully. I think having the initial hand overlay when opening the Factor screen really helped. Students realized they were supposed to touch the board. When they saw the hand again later in the corner, they instinctively knew to touch it.
