### ISSUE TITLE
Add a temporary pointer indication to the multiplication table on the factor screen

### ISSUE THREAD

**Issue by jbphet** [phetsims/arithmetic#119]
From the 1/15/2015 design meeting notes:

To cue touchability on factor screen, overlay a subtle transparent hand over grid that disappears once grid is touched. Kind of like this: 
![temp](https://cloud.githubusercontent.com/assets/3082831/5827236/05998a58-a0b6-11e4-9b94-cef8d9475d6e.png)

**Comment by jbphet** [comment]
This has been added and was interviewed on, so I'm assigning to @amanda-phet so that she can decide if it worked as intended.  If so, the issue can be closed.

**Comment by amanda-phet** [comment]
It absolutely worked.
