### ISSUE TITLE
Factor screen should behave a little differently when a correct answer is chosen

### ISSUE THREAD

**Issue by jbphet** [phetsims/arithmetic#120]
From @ariel-phet via email:

I did notice one minor tweak when using a mouse on the factor screen:

If you get an answer right and then don't move your mouse, the purple boxes disappear and don't return until you move your mouse again. Take a look, it seems like it might feel smoother to just leave the purple boxes and then have the hand in the corner box appear when you move your mouse.

**Comment by jbphet** [comment]
This was recently interviewed on.  Assigning to @amanda-phet, who conducted the interviews, so that she can comment on how this worked and decide whether the issue is resolved.

**Comment by amanda-phet** [comment]
I interviewed only on iPads and this seems mouse-specific. However when I use the factor screen with a mouse I find this behavior natural. In the Multiply and Divide screens the purple boxes disappear/move when the next problem is stated, so I think it makes sense that they should similarly disappear here. 

Should I do one more interview but on a laptop?

**Comment by ariel-phet** [comment]
If @amanda-phet finds the behavior natural, I am satisfied, closing.
