### ISSUE TITLE
Girl has no mouth in multiply level selection

### ISSUE THREAD

**Issue by phet-steele** [phetsims/arithmetic#121]
I've looked on multiple devices with different resolutions, as well as different browsers, but the girl's mouth is just incredibly hard to see.

![arithmetic girl has no mouth](https://cloud.githubusercontent.com/assets/5863899/5881929/36e3f67c-a302-11e4-84ed-bef4f18aa7a1.png)

1.0.0-dev.12

**Comment by jbphet** [comment]
Assigning to @ariel-phet to see if he wants to work with the graphic artist to address this.  I've scaled the image pretty carefully, and verified that it was exported using the "Art Optimized" anti-aliasing setting.  The original artwork just uses a thin stroke for the smile, and it pretty much disappears when the image is scaled.

**Comment by jbphet** [comment]
Discussed this with @ariel-phet and decided that I'd modify the artwork to see if I can fix this.

**Comment by jbphet** [comment]
This sim is on hold for a while, so I'm unassigning this issue until work resumes.

**Comment by jbphet** [comment]
In general, I think all of the usages of the PhET Girl icons can be made to look better by using mipmaps.  I'll start with that, and then mod the artwork if still necessary.

**Comment by jbphet** [comment]
I ended up modding the artwork, saving larger versions of the icons, and converting the icons to mipmaps.  It looks much better now.  Closing.
