### ISSUE TITLE
Multiple Points per Answer

### ISSUE THREAD

**Issue by phet-steele** [phetsims/arithmetic#122]
After an answer is submitted, further clicks on the yellow button will register as correct answers. This is only in multiply and divide levels. Tested originally on Win 8.1 64-bit browsers, 1.0.0-dev.12

Yes I used an auto-clicker in this video, it was too good an opportunity to pass up:
https://drive.google.com/file/d/0B3HJopSo_QqLMmFCRU5sSF80bHM/view?usp=sharing

**Comment by jbphet** [comment]
Yikes.  Definitely needs to be addressed.

**Comment by jbphet** [comment]
This could be fixed by putting a check of the game state around the code that submits the answer, but because we are now planning to redesign the keypad to no longer have an enter key (see #130), this becomes a non-issue.  Closing.
