### ISSUE TITLE
User is able to score multiple points in Factor mode

### ISSUE THREAD

**Issue by bryo5363** [phetsims/arithmetic#123]
Test device: MacBook Pro

Operating System: 10.10.1

Browser: Chrome 40.0.2214.91 (64-bit)

Problem description: The user is able to generate multiple points in the Factor mode

Steps to reproduce:
-Open sim in factor mode
-Start clicking correct answers
-Let's say the question asks _ X _ = 6. If you initially put 2 x 3, wait for the reward node and enter 1 x 6. The user will get 2 points even though 1 x 6 will not become highlighted. 
Severity:

Screenshots:

Troubleshooting information (do not edit):
Name: Arithmetic
URL: http://www.colorado.edu/physics/phet/dev/html/arithmetic/1.0.0-dev.12/arithmetic_en.html
Version: 1.0.0-dev.12
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.91 Safari/537.36
Language: en-us
Window: 1050x570
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 8192 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 8192x8192
OES_texture_float: true

**Comment by jbphet** [comment]
Nice.  Probably related to #122.  I'll investigate and fix.
