### ISSUE TITLE
Levels do not reset after completion

### ISSUE THREAD

**Issue by bryo5363** [phetsims/arithmetic#124]
Test device: MacBook Pro

Operating System: OSX 10.10.1

Browser: Chrome 40.0.2214.91 (64-bit)

Problem description: Levels do not reset after completiong

Steps to reproduce:
-open sim w/ any mode
-complete a level 
-reopen level. None of the entries are cleared from the board. 
Severity:

Screenshots:

Troubleshooting information (do not edit):
Name: Arithmetic
URL: http://www.colorado.edu/physics/phet/dev/html/arithmetic/1.0.0-dev.12/arithmetic_en.html
Version: 1.0.0-dev.12
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.91 Safari/537.36
Language: en-us
Window: 1050x570
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 8192 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 8192x8192
OES_texture_float: true

**Comment by phet-steele** [comment]
Note that once an answer is inputted, the board clears and the score gets reset.

**Comment by phet-steele** [comment]
Most likely related: reset all does not clear the boards either.

**Comment by jbphet** [comment]
Will investigate.

**Comment by jbphet** [comment]
This sim is on hold for a while, so I'm unassigning this issue until work resumes.

**Comment by jbphet** [comment]
The general behavior has been changed so that a level doesn't reset until the user explicitly refreshes the board, see #129.  This new behavior has been implemented, effectively making this issue obsolete.  Closing.
