### ISSUE TITLE
Reward node is extremely fast on OSX 10.10.1

### ISSUE THREAD

**Issue by bryo5363** [phetsims/arithmetic#125]
Test device: MacBook Pro

Operating System: OSX 10.10.1

Browser: Chrome 40.0.2214.91 (64-bit)

Problem description: Reward node happens extremely fast. I was talking with @phet-steele about reward nodes occurring very quickly and he said he did not notice this behavior on his computer (Windows 8.1)

Steps to reproduce:
-open sim
-get a correct entry
Severity:

Screenshots:

Troubleshooting information (do not edit):
Name: Arithmetic
URL: http://www.colorado.edu/physics/phet/dev/html/arithmetic/1.0.0-dev.12/arithmetic_en.html
Version: 1.0.0-dev.12
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.91 Safari/537.36
Language: en-us
Window: 1050x570
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 8192 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 8192x8192
OES_texture_float: true

**Comment by phet-steele** [comment]
I found that this is reproducible after multiple, quickly successive wrong answers. The reward node will fade quickly on Win 8.1 when this is done.

**Comment by jbphet** [comment]
I reproduced with with @phet-steele by clicking a bunch of times on an incorrect answer in the Factor screen.  Once the fade becomes quick, it's always quick thereafter, for both correct and incorrect answers.  This should be fixed.  Assigning to myself to address.
