### ISSUE TITLE
Weird purple square shading

### ISSUE THREAD

**Issue by phet-steele** [phetsims/arithmetic#127]
This happens in factor and is quite tricky:

Reproduction (touch screen):
1. Touch the square that is the correct answer but don't answer it (touch requires a double tap to answer).
2. This is quick so plan ahead: Touch the square again to answer then quickly touch a different square then hold your finger on a square (same or different, doesn't matter). This step is three movements: tap correct square to answer -> tap a different square -> tap and hold a square
3. Release your hold a few seconds after the reward node fades away.

Video of my hand movements:
https://drive.google.com/file/d/0B3HJopSo_QqLVVB3R2xrc2ZNRm9lb0ZLT05zWlhxWm5CVmkw/view?usp=sharing

Mouse reproduction has similar movements, aside from not needing to do step one since no double click is needed to answer. Using a mouse also yields different results.

The first half of this video shows what happens with a touch screen. The latter half shows what happens with a mouse.
https://drive.google.com/file/d/0B3HJopSo_QqLeENpaGk2Z1NXX1k/view?usp=sharing

Testesd in 1.0.0-dev.12 on iPad 2 and Asus (Win 8) touch screens.
Troubleshooting information:
Name: Arithmetic
URL: http://www.colorado.edu/physics/phet/dev/html/arithmetic/1.0.0-dev.12/arithmetic_en.html
Version: 1.0.0-dev.12
User Agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.16 Safari/537.36
Language: en-us
Window: 1366x681
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 28 uniform: 1024
Texture: size: 8192 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 8192x8192
OES_texture_float: true

**Comment by jbphet** [comment]
I worked on reproducing it with @phet-steele in the room.  It's hard to reproduce and doesn't cause anything horrible when it happens.  Not too sure that it needs fixing.  Assigning to @amanda-phet to see if she concurs.  If so, she can just close.

**Comment by amanda-phet** [comment]
I had a difficult time reproducing this and think that if a student encounters this issue they are probably just clicking around randomly (which by the way also reproduced it for me) and will quickly click again to "exit" out of this odd bug.
