### ISSUE TITLE
Shaded squares don't follow mouse

### ISSUE THREAD

**Issue by phet-steele** [phetsims/arithmetic#128]
In the factor levels, the squares will not get shaded purple at the mouse location after the reward node disappears, until the mouse is moved to a different square. This implies getting a correct answer.

Here's what I mean:
https://drive.google.com/file/d/0B3HJopSo_QqLdkVpSERLY01Bb2M/view?usp=sharing

Tested on Win 8.1 browsers in 1.0.0-dev.12
Troubleshooting information:
Name: Arithmetic
URL: http://www.colorado.edu/physics/phet/dev/html/arithmetic/1.0.0-dev.12/arithmetic_en.html
Version: 1.0.0-dev.12
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0
Language: en-US
Window: 1366x633
Pixel Ratio: 1/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 10 uniform: 254
Texture: size: 16384 imageUnits: 16 (vertex: 4, combined: 20)
Max viewport: 16384x16384
OES_texture_float: true

**Comment by jbphet** [comment]
We had made a decision to leave the selected squares set while the feedback is being shown.  @phet-steele is noting that if the user moves the mouse into a new square before feedback is finished, the square doesn't light up after the feedback.  This wouldn't be *too* hard to fix, but I'm not sure it's worth it.  Most users will move the mouse more than one square, and are unlikely to be confused by this behavior.

My vote is to not worry about this.  Assigning to @amanda-phet for her input.

**Comment by amanda-phet** [comment]
I reproduced it and thought it was very subtle. I don't find this behavior to be unsettling so I vote to worry about larger issues. In interviews, I did not see problems with this (although I was interviewing solely on iPad).

**Comment by amanda-phet** [comment]
Can we close this issue? @ariel-phet do you have an opinion?

**Comment by jbphet** [comment]
This sim is on hold for a while, so I'm unassigning this issue until work resumes.

**Comment by jbphet** [comment]
@amanda-phet said, "I vote to worry about larger issues".  I agree.  Closing.
