### ISSUE TITLE
Redesign keypad

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/arithmetic#130]
In two interviews I noticed students struggle with finding the "enter" button on the keypad. One student even accidentally pushed it two times, thinking it was the "backspace" button. 

I suggest using the keypad from Area Builder, if it is not too difficult, because that one has proven to be successful already. I especially like that the submit/check button is larger and more obviously not part of the keypad. I am also for standardizing the keypad across sims. 

Thoughts- @ariel-phet @jbphet ? 

Here is a basic mockup: 
![screen shot 2015-01-30 at 10 30 33 am](https://cloud.githubusercontent.com/assets/7852916/5980176/130d685a-a86b-11e4-87a8-7dc9b8c7eb9d.png)

**Comment by ariel-phet** [comment]
Seems like the right call, since the area builder design is well vetted. Assigning to @jbphet

**Comment by jbphet** [comment]
A couple of decisions were made at the 2/5/2015 design meeting:
+ Move forward with this.
+ Reposition the "Try Again" button to be in the same location as the check button.
+ The Factor screen, which has no keypad, should have the "Try Again" button in the same place as the other two screens.

**Comment by jbphet** [comment]
This sim is on hold for a while, so I'm unassigning this issue until work resumes.

**Comment by jbphet** [comment]
Implemented, closing.
