### ISSUE TITLE
Build fails - missing changes.txt

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/arithmetic#133]

**Comment by pixelzoom** [comment]
@jonathanolson Just curious... Why would a build fail if change.txt is missing? It's not a file that's required by the grunt build task.

**Comment by jonathanolson** [comment]
Chipper's gruntfile would disagree:

```js
    grunt.log.writeln( 'Copying changes.txt' );
    if ( fs.existsSync( 'changes.txt' ) ) {
      grunt.file.copy( 'changes.txt', 'build/changes.txt' );
    }
    else {
      grunt.log.error( 'WARNING: no changes.txt' );
    }
```

IIRC, the grunt.log.error changes the exit code of the process to something other than 0, so the automatic test harness thinks it's a hard failure.
