### ISSUE TITLE
Pointing hand is not annotated in license.txt

### ISSUE THREAD

**Issue by samreid** [phetsims/arithmetic#138]
I can see that @jbphet checked in the AI file but it is not clear whether this artwork was drawn by our team or obtained from a 3rd-party and hence subject to their licensing.  @jbphet do you know where this image came from?

See https://github.com/phetsims/tasks/issues/274

![image](https://cloud.githubusercontent.com/assets/679486/8785809/73f2b7da-2ee7-11e5-9e7e-258207f9aa4c.png)

**Comment by amanda-phet** [comment]
This was created by Bryce.

**Comment by samreid** [comment]
Thanks @amanda-phet, closing.
