### ISSUE TITLE
Factor screen does not allow you to try again without clicking Try Again button

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/arithmetic#143]
After doing some detective work, it looks like #107 states that we added a Try Again button for the Factor screen, but still wanted to be able to submit another answer without requiring that we click on Try Again. 

>>Factor screen: Fill in equation with answers and shows ≠. Freeze answer in grid, press try again (or tap anywhere on the grid to “release” the frozen state, then you can move your mouse around as before).  

This is enabled in dev.12 but disappeared by dev.13 (and of course later versions). 

I can not find another issue relating to this that made us change our mind about the behavior. If any team members (@ariel-phet @kathy-phet @dubson) can remember if we consciously changed this or not, please let us know. I would like it to be re-implemented. 

@jbphet and I discussed and think it would be beneficial to be able to submit an answer without clicking on Try Again (especially when using a cursor) so he will see if there's something in the commits between January and February that eliminated this behavior.

**Comment by ariel-phet** [comment]
@amanda-phet I think that paradigm follows what we have instituted in many other games since deciding to have this sort of behavior in area builder. I see no reason not to have it in arithmetic as well.

**Comment by jbphet** [comment]
I'll assign this to myself and start working on it, and will raise a flag if I come across anything that indicates that we had a good reason for *not* doing it this way before.

**Comment by jbphet** [comment]
I added this, and it was fairly isolated and straightforward to do so.  This makes me a little suspicious that there was some reason not to do it before.  I'll wait to close until tested on iPad (don't have one available at the moment).

**Comment by jbphet** [comment]
I tested the modified retry behavior for the factor screen on version 1.0.0-dev.16 (http://www.colorado.edu/physics/phet/dev/html/arithmetic/1.0.0-dev.16/arithmetic_en.html) and it appears to work fine.  Assigning to @amanda-phet to verify on desktop and iPad.

**Comment by amanda-phet** [comment]
This is working well for me on a macbook but I will not be able to verify on an iPad. Should I ask an undergrad to verify?

**Comment by phet-steele** [comment]
Good to go in 1.0.0-dev.17 (iPad 3 DiSessa).
