### ISSUE TITLE
odd behavior if back button is pressed while feedback is being shown

### ISSUE THREAD

**Issue by jbphet** [phetsims/arithmetic#145]
If the user submits an answer and then immediately presses the back button, sometimes it doesn't work, and other times the animation back to the level selection screen starts but then animates back to the multiplication board.  This can be duplicated on this version: http://www.colorado.edu/physics/phet/dev/html/arithmetic/1.0.0-dev.16/arithmetic_en.html.

**Comment by phet-steele** [comment]
In 1.0.0-dev.17, the animation is working fine. But if sound is on and the above protocol is followed, a second of @jbphet's kitchen glasses will ding upon returning to the level that was just left.

**Comment by jbphet** [comment]
Nice catch @phet-steele.  This was due to some refactoring where the playing of sounds was moved out of the model and into the view.  I've added code to more completely qualify the state transitions necessary to trigger the sound.

**Comment by jbphet** [comment]
Tested this on v1.0.0-rc.1 to make sure that this was fixed, and the behavior now appears correct.  Closing.
