### ISSUE TITLE
Reset button does not reset clock settings or sound settings

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/arithmetic#147]
I suspect this is more of a design question, but if you change the settings of clock and sound from the default: clock off, sound on, hitting the reset button leaves the clock and sound settings un changed.

**Comment by jbphet** [comment]
I just discussed with with @ariel-phet, @amyh-phet, and @arouinfar, and we agreed that the reset button should reset the sound and timer enabled properties.  These are global for the sim, so resetting on one screen (e.g. Divide) resets it for all screens.

**Comment by phet-steele** [comment]
Fixed in 1.0.0-dev.17 (Win 8.1/Chrome).
