### ISSUE TITLE
Answer entry behaviour while switching between levels

### ISSUE THREAD

**Issue by phet-steele** [phetsims/arithmetic#151]
The extreme of this issue (step 5) is most likely not a reasonable use case, but I'm still reporting this @jbphet since it could lead to some undesired wrong answers!

1. On either the Multiply or Divide screens, pick a level and type in an answer (don't submit it!). Typing a one or two digit number makes this issue cooler.
2. Click the back button.
3. Return to the SAME level. Switching levels doesn't make this issue happen the same way.
4. You'll be presented with a new question and a presumably empty answer field. Instead, the sim remembers your old entry, so typing in another number reveals the number(s) you typed in earlier. Someone quickly answering and pressing "Check" may not notice this and get the wrong answer.
5. Repeating this until you have all three numbers in the field and doing steps 2 & 3 again, the user can no longer type anything into answer fields since they've hit the three digit max.

![arth2](https://cloud.githubusercontent.com/assets/5863899/11597470/247e8eb0-9a79-11e5-82fd-9cc67c0fa0c6.gif)

What's interesting to me is step 3. Why is there different behaviour after pressing back if I click on a different level vs. the same level? If I follow this order:
Level 1 -> back -> Level 2 -> back -> Level 1
the original answer that was typed in is saved and presented, but this order:
Level 1 -> back -> Level 1
hides my answer and leads to this issue. 

But the even BIGGER question here is why does the sim give me a new question every time? I feel like it should be the question I left behind after returning to the level. Tested on my personal device with Win 8.1 Chrome.

Troubleshooting information:
Name: ‪Arithmetic‬
URL: http://www.colorado.edu/physics/phet/dev/html/arithmetic/1.0.0-dev.16/arithmetic_en.html
Version: 1.0.0-dev.16 2015-12-01 22:20:53 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.73 Safari/537.36
Language: en-US
Window: 1366x643
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"arithmetic":{"sha":"da928fe4","branch":"master"},"assert":{"sha":"3921bc37","branch":"master"},"axon":{"sha":"fffc6c30","branch":"master"},"babel":{"sha":"90f9f553","branch":"master"},"brand":{"sha":"c9282935","branch":"master"},"chipper":{"sha":"b1b72ba8","branch":"master"},"dot":{"sha":"b8ec76e8","branch":"master"},"joist":{"sha":"3bd993e7","branch":"master"},"kite":{"sha":"a4907ccc","branch":"master"},"phet-core":{"sha":"73a034c6","branch":"master"},"phetcommon":{"sha":"e074b239","branch":"master"},"scenery":{"sha":"596fce54","branch":"master"},"scenery-phet":{"sha":"ab056b47","branch":"master"},"sherpa":{"sha":"be8c4fc9","branch":"master"},"sun":{"sha":"bf8586ef","branch":"master"},"tandem":{"sha":"e98bd8c3","branch":"master"},"vegas":{"sha":"b7bb8c39","branch":"master"},"vibe":{"sha":"f09e9c6e","branch":"master"}}

**Comment by jbphet** [comment]
This was fixed when working on #145 and #148, since it related to how the model behaved when going back to the level selection screen.  The commits associated with those issues can be viewed if detail is needed about how the solution works.  In summary, the code now only sets up a new problem upon transition into a levelwhen the previous problem had been finished.

**Comment by phet-steele** [comment]
Answers entries get reset and new answers don't show up when switching levels! :+1: Fixed in 1.0.0-dev.17 (Win 8.1/Chrome).
