### ISSUE TITLE
Factor may let you click numbers that have already been filled in

### ISSUE THREAD

**Issue by brroberts1231** [phetsims/arithmetic#153]
Test device:Galileo

Operating System: Windows 10

Browser: Edge

Problem description: Sometimes the factor game will highlight numbers that have already been filled in to say that you may click on it, possibly resulting in a wrong answer if you click it accidentally, or being able to click on a number twice to get a correct answer (when you are given 48, and you click on a 48 that is already there, it will give you credit). The normal behavior is that it will not highlight numbers that have already been filled in but if you press the arrow to back out of the game and come back in, some numbers that have been filled in will be highlighted when you mouse over them(any numbers you filled in before going back will highlight, any you fill in after coming back into the game will behave normally.)

Steps to reproduce: Open a factor game, and fill in some numbers. Press the arrow to back out of the game, then click back into it. The numbers you had filled in will now highlight, and any new ones you fill in will not. If you get a number come up that you have already filled in before, you can click on the one that is already there and it will tell you that it is correct. Also, you can click on a number that is already there and be told it is incorrect if it is in the wrong spot (say you are given 12 and click on a 5 that has been filled in), whereas normally you wouldn't be able to click it.

Severity:

Screenshots: 48 is already filled in
![screenshot1](https://cloud.githubusercontent.com/assets/11947677/11601886/acad41fe-9a93-11e5-92d4-826dd6125128.png)
but I can click 48 again
![screenshot2](https://cloud.githubusercontent.com/assets/11947677/11601939/ea001c5c-9a93-11e5-88d7-fa7510c984ae.png)
and it will tell me it is correct.
![screenshot3](https://cloud.githubusercontent.com/assets/11947677/11601950/fd414570-9a93-11e5-9914-82427172b649.png)
Ignore that stringTest=double and dev happen to be on, they are not part of this issue.

Troubleshooting information (do not edit):

Name: ‪Arithmetic‬:‪Arithmetic‬

URL: http://www.colorado.edu/physics/phet/dev/html/arithmetic/1.0.0-dev.16/arithmetic_en.html?dev&stringTest=double

Version: 1.0.0-dev.16 2015-12-01 22:20:53 UTC

Features missing: touch

Flags: pointerEnabled, pixelRatioScaling

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10240

Language: en-US

Window: 1536x710

Pixel Ratio: 1.25/1

WebGL: WebGL 0.95

GLSL: WebGL GLSL ES 0.95

Vendor: Microsoft (Internet Explorer)

Vertex: attribs: 16 varying: 15 uniform: 512

Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)

Max viewport: 16384x16384

OES_texture_float: true

Dependencies JSON: {"arithmetic":{"sha":"da928fe4","branch":"master"},"assert":{"sha":"3921bc37","branch":"master"},"axon":{"sha":"fffc6c30","branch":"master"},"babel":{"sha":"90f9f553","branch":"master"},"brand":{"sha":"c9282935","branch":"master"},"chipper":{"sha":"b1b72ba8","branch":"master"},"dot":{"sha":"b8ec76e8","branch":"master"},"joist":{"sha":"3bd993e7","branch":"master"},"kite":{"sha":"a4907ccc","branch":"master"},"phet-core":{"sha":"73a034c6","branch":"master"},"phetcommon":{"sha":"e074b239","branch":"master"},"scenery":{"sha":"596fce54","branch":"master"},"scenery-phet":{"sha":"ab056b47","branch":"master"},"sherpa":{"sha":"be8c4fc9","branch":"master"},"sun":{"sha":"bf8586ef","branch":"master"},"tandem":{"sha":"e98bd8c3","branch":"master"},"vegas":{"sha":"b7bb8c39","branch":"master"},"vibe":{"sha":"f09e9c6e","branch":"master"}}

**Comment by brroberts1231** [comment]
Also, you can use this to keep raising your score beyond what the upper limit should be. On level 1, the highest score you should be able to get is 36, but you can keep raising it higher than that by clicking a number that's already there, clicking back and coming back in. I left the last number open, so it keeps giving me 3, I'll click the 3 that's already there, back out and come back in, and repeat. The menu will keep adding stars to keep up with the higher score.
![screenshot4](https://cloud.githubusercontent.com/assets/11947677/11602315/8534f6a0-9a96-11e5-8f80-f65cf467d33d.png)

**Comment by phet-steele** [comment]
Fixed in 1.0.0-dev.17 (Win 8.1/Chrome).
