### ISSUE TITLE
Once 1.0 is published, copy and replace testing matrix document

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/arithmetic#161]
The current testing matrix is owned by @jbphet on his colorado.edu account, so ownership cannot be switched to phethelp@gmail 

Once testing for 1.0 is finished and the sim has been published, please copy over the test matrix to a spreadsheet created on the gmail domain, so that onwership can be switched to phethelp.

**Comment by jbphet** [comment]
This is done, and I've changed the ownership to phethelp@gmail.com as well.  Link: https://docs.google.com/spreadsheets/d/1hCiHBZfkbpSC11eee132eQB4ezPwc92X5DOGIU0gaVE/edit#gid=939297902.  Closing.
