### ISSUE TITLE
Add title to scoreboard panel

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/arithmetic#162]
@ariel-phet had a suggestion for one extra way to differentiate the similar-looking screens. We'd like to add a title to the scoreboard panel that says either Multiply, Factor, or Divide. 

After previewing this with @jbphet it seems to fit well and will be simple to implement. It will look something like this mockup: 
<img width="809" alt="screen shot 2015-12-14 at 12 42 02 pm" src="https://cloud.githubusercontent.com/assets/7852916/11791804/127f6d12-a260-11e5-847f-ffc8a34a91ef.png">

**Comment by jbphet** [comment]
Assigning to @amanda-phet to verify on v1.0.0-rc.2, available here: http://www.colorado.edu/physics/phet/dev/html/arithmetic/1.0.0-rc.2/arithmetic_en.html.

**Comment by amanda-phet** [comment]
Looks great to me!
