### ISSUE TITLE
After completing level, should sim automatically redirect to level selection screen?

### ISSUE THREAD

**Issue by arouinfar** [phetsims/arithmetic#163]
So far things are looking good on OSX 10.11. I have a quick question that maybe @ariel-phet @amanda-phet or @jbphet could answer. After completing a level, the sim does not automatically redirect me to the level selection screen. I found this behavior a bit strange, since it is contrary to our regular game mechanics. I can see some pedagogical reasons why the design team may have decided to keep the completed multiplication table visible on screen, but I thought I would bring it up in case this is not the desired behavior.

Final score shown after completing a level
![image](https://cloud.githubusercontent.com/assets/8419308/11792943/2053a4f2-a266-11e5-9be1-1f16f06f7940.png)

Clicking continue keeps you on the same page
![image](https://cloud.githubusercontent.com/assets/8419308/11792960/314674ce-a266-11e5-888b-116d257bfcd0.png)

**Comment by ariel-phet** [comment]
Definitely a question for @amanda-phet - I noticed this behavior as well. Returning to the level selection screen certainly would work, but was there a reason for this behavior? So that the student could look over what they had done?

**Comment by amanda-phet** [comment]
@arouinfar it was intentional so that students can reflect on the finished board, and also because in this game, clicking on the level again will bring you to a completed board as opposed to starting fresh.

**Comment by arouinfar** [comment]
That's what I suspected. Thanks for confirming @amanda-phet! I'll go ahead and close this issue.
