### ISSUE TITLE
Updated teacher tips and move over activities?

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/arithmetic#167]
Arithmetic needs an updated teacher tips now that we have an HTML5 version. In addition, it might be good to see if any of the activities can be moved over without changes.

@amanda-phet if you see an activity (from us) that could be moved over with some minor tweaks, let me know. Might be a good task for Elise or Steele.

**Comment by amanda-phet** [comment]
Most of the activities were fine to move over (many are just sim alignment docs) so that is taken care of. 

I'll keep this open until I make a teacher tips document.

**Comment by jbphet** [comment]
I just took a look at the first activity listed, and there is something incorrect in it.  It says:
>With the clock off, the students will get a final score calculated by correct minus incorrect.  With the clock on, the score is the (number right-number wrong)/time in seconds times 60 or (final score)/time*60.
This is no longer how the score is calculated.  You now get one point for an answer the is correct the first time, zero points for answers that are incorrect on the first attempt, and the clock does not factor in to the score calculation.  This should probably be updated.

**Comment by amanda-phet** [comment]
Thanks for looking that closely! I basically just looked for screenshots and general instructions. I will talk to Trish about updating it (I don't think she would mind if we edit it but I'd like to double-check first).

**Comment by phet-steele** [comment]
@amanda-phet I've made the teacher tips.

**Comment by amanda-phet** [comment]
I updated this activity a while ago but didn't remember this issue existed. Closing.
