### ISSUE TITLE
User request: Allow entry of answers from the keyboard

### ISSUE THREAD

**Issue by jbphet** [phetsims/arithmetic#171]
@oliver-phet forwarded me an email with following contents:

> Another user reported to phethelp:
> on the new arithmetic simulation (both online and on the download), I am unable to type in the answer to the problems. I can only use the on-screen number box. I had no such problem with the legacy version. Is there any way to fix this?

**Comment by oliver-phet** [comment]
I added it to the old issue: https://github.com/phetsims/arithmetic/issues/7

**Comment by jbphet** [comment]
I just realized that this is a duplicate of #7, so I'll close this and reopen the old one.
