### ISSUE TITLE
autoAnswer only works the first time you play a game

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/arithmetic#172]
I was using the autoAnswer query parameter to test some behavior in this sim.  Surprised to find that it only works the first time you play a level, making it difficult to test things like best time.  Sure would be useful if it filled in the answers consistently.

**Comment by jbphet** [comment]
Interesting that no one ever noticed this before, or at least weren't concerned about it.  It was fairly easy to make the auto-answer kick in on a refresh of a level, which is what I think @pixelzoom was looking for.  Assigning back to him to first verify that the functionality supports the testing he was doing, and second to inspect the code changes.

**Comment by pixelzoom** [comment]
Yep, exactly what I was looking for. Thanks. Closing.
