### ISSUE TITLE
Make random sequences reproducible

### ISSUE THREAD

**Issue by samreid** [phetsims/arithmetic#176]
From https://github.com/phetsims/phet-io/issues/548, we saw that arithmetic uses _.shuffle and _.sample and Math.random.  These should be replaced with re-seedable alternatives for deterministic phet-io playback.

**Comment by samreid** [comment]
@jbphet the git history suggests you are the liaison for this simulation.  Can you please review the changes above and see if they are correct and complete?

**Comment by jbphet** [comment]
I had the follow Skype conversation with @samreid:

> [12:03:37 PM] @jbphet: I'm looking at https://github.com/phetsims/arithmetic/commit/83bda69e3c31fd5dcf2c5016c154bbfaf70e60da and wondering why you chose to create a Random instead of using phet.joist.random.x.  Any reason, or just the feeling of the moment?
> [12:04:16 PM] @samreid : phet.joist.random would be better
> [12:04:41 PM] @samreid: phet.joist.random was invented afterwards, and I neglected to go back and updated that code
> [12:06:35 PM] @jbphet: Ah, okay, that makes sense.  I'll mod this then.
> [12:06:44 PM] @samreid: thank you!

I've made that mod and tested the sim, and it all looks good.  Closing.
