### ISSUE TITLE
disable autoAnswer

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/arithmetic#182]
See https://github.com/phetsims/joist/issues/406.

Add this to ArithmeticQueryParameters:

```js
if ( phet.chipper.isProduction && !phet.chipper.isDebugBuild ) {
  ArithmeticQueryParameters.autoAnswer = false;
}
```

**Comment by jbphet** [comment]
I added the suggested code and removed the previous code that prevented the feature from being available in production builds based on the version ID.  Closing.
