### ISSUE TITLE
Convert from TWEEN to Twixt

### ISSUE THREAD

**Issue by samreid** [phetsims/arithmetic#184]
As discussed in https://github.com/phetsims/joist/issues/387#issuecomment-419600722, it would be nice to use Twixt instead of TWEEN.  This sim has 3 occurrences of `new TWEEN.Tween(...)`.  Assigning to the responsible dev.  After completing this issue, check if the hold on https://github.com/phetsims/joist/issues/387 can be removed (if this was the last "Convert from TWEEN to Twixt" issue).

**Comment by jbphet** [comment]
Usages replaced (which involved some rewriting), preloads removed.  Tested the animations manually and via fuzz testing.  Did a basic memory leak test and didn't see anything that appeared to be related to the new animations.  Should be good to go, closing.
