### ISSUE TITLE
Initial PhET-iO instrumentation

### ISSUE THREAD

**Issue by samreid** [phetsims/arithmetic#185]
As discussed today, we are interested in initial PhET-iO instrumentation that at a minimum provides the user-submitted answers.  @chrisklus volunteered to assist.

**Comment by samreid** [comment]
@zepumph suggested creating a simple wrapper that adds a listener to the 3 emitters, that the client could use as a starting place.

**Comment by zepumph** [comment]
>@zepumph suggested creating a simple wrapper that adds a listener to the 3 emitters, that the client could use as a starting place.

see #2 

Unassigning for now.

**Comment by samreid** [comment]
I think we may need guidance from @kathy-phet before working on this further.

**Comment by zepumph** [comment]
@kathy-phet said today that she pinged the client this week, and we are waiting back to hear what else is needed.

**Comment by chrisklus** [comment]
From 08/29/19 phet-io meeting - when we start instrumentation we'll open a new design issue, ready to close here.
