### ISSUE TITLE
Promote EmitterIO args to top-level

### ISSUE THREAD

**Issue by samreid** [phetsims/arithmetic#187]
As described in https://github.com/phetsims/axon/issues/184#issuecomment-428770937.  We would like to specify the emitter args like so: https://github.com/phetsims/axon/issues/184#issuecomment-428775196

@zepumph can you please address this?  I'll mark this for blocks-sim-publication but not block-publication.  Or let me know if you prefer me or @chrisklus work on this.

**Comment by zepumph** [comment]
Implemented above, tested in both brands by fuzzing and by looking at the data stream output. Notice the added doc. I saw that the `Property.<number>` were initialized to `undefined`. After looking though all places where they were set, I determined it was safe to still validate them as NumberIO, but I added a comment. @samreid please review.

**Comment by samreid** [comment]
Looks great, thanks!  Closing.
