### ISSUE TITLE
Long screen titles

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/arithmetic#189]
I noticed that long screen title strings go off the screen. I checked the submitted translations and none seemed to be a problem, so this can probably be closed or deffered until this comes up.
![12345678901234567890123456789012345678901234567890 screenshot](https://user-images.githubusercontent.com/41024075/72547230-7aaabf80-3849-11ea-8051-f0e2c66e41c0.png)

**Comment by jbphet** [comment]
Let's defer until this sim is re-released off of master.  It's probably just a matter of setting a `maxWidth` somewhere, so should be a quick fix.

**Comment by marlitas** [comment]
This will be addressed as part of the dynamic locale work for the region and culture publication. Removing deferred label and self-assigning.

**Comment by marlitas** [comment]
This was addressed in #199. Closing
