### ISSUE TITLE
Non-interactive parts of the equation have blinking cursor

### ISSUE THREAD

**Issue by jbphet** [phetsims/arithmetic#192]
While regression testing during work for #191, I noticed that the non-interactive portions of the equation now have a blinking cursor.  It looks like this:

![arith-cursors](https://user-images.githubusercontent.com/3082831/99855677-93a88f00-2b44-11eb-8707-8f6f2c6fd471.gif)

Only the sum is interactive in this case, and only that cursor should be blinking.  This can be compared to the current published version if desired.

@jonathanolson - this problem was introduced in 6e26e872811593e17c959fc039ee56f482c9fb6c, which looks like it was related to dynamic layout issues.  I'm not sure what you were after here, so please take a look and see if there's a better way to accomplish your goal without breaking the sim's behavior.

**Comment by jonathanolson** [comment]
Apologies! I missed that the visibility of the cursor itself was being toggled. Thank you for finding it, should be fixed with the above.
