### ISSUE TITLE
Decide whether to turn off UI sounds on next publication

### ISSUE THREAD

**Issue by markgammon** [phetsims/arithmetic#194]
As part of the work done for https://github.com/phetsims/vegas/issues/77, UI sounds got turned on for this simulation.  Before the sim is published again from master, we should decide whether to turn the UI sounds off, leave them on and design and implement sounds for the rest of the interactions, or publish with a partial sound design.

If the decision is to turn them off, this can be accomplished by adding the following line to the end of the sim's `-main.js` file:

```js
  soundManager.setOutputLevelForCategory( 'user-interface', 0 );
```

**Comment by marlitas** [comment]
I am assuming completing sound design is not part of the work that should be included in the upcoming region and culture publication. I'll self assign to turn off. @kathy-phet let me know if I assumed incorrectly and we will be adding sound to this sim.

**Comment by AgustinVallejo** [comment]
In the above commit I changed the default RefreshButton sound for the new eraser sound. Assigning back to @marlitas for her (or somebody else) to make sure it's what you guys wanted.

**Comment by AgustinVallejo** [comment]
@amanda-phet commented on Slack:

> Yes, I think it would be a nice update to replace that button with the eraser button!

Will do

**Comment by AgustinVallejo** [comment]
Added the requested changes. The only thing that seems off is the spacing inside the Panel, which seems different to the published version. I'm adding screenshots for published, main branch before the above commits, and main branch after commits.

![image](https://github.com/phetsims/arithmetic/assets/37052186/6791f458-8f0b-4ba0-8717-32b06b0829ae)

@marlitas @amanda-phet Please review these changes and let me know if something should be done about that spacing.

**Comment by amanda-phet** [comment]
Eraser button looks and sounds good!
