### ISSUE TITLE
Consider converting to default layoutBounds before PhET-iO publication

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/arithmetic#197]
This sim currently uses non-default `layoutBounds`.  In ArithmeticView.js:

```js
    super( { layoutBounds: new Bounds2( 0, 0, 768, 504 ) } );
```

Per https://github.com/phetsims/phet-io/issues/1939...  `layoutBounds` should not be changed for published PhET-iO sims because doing so may disrupt client customizations. So evaluate whether to change `layoutBounds` before publishing a PhET-iO version. 

If you decide not to change layoutBounds, document why in ArithmeticView.js, and refer to this issue.

**Comment by marlitas** [comment]
hmmm... I am not sure if this should be part of the region and culture work. It seems like non-default layoutBounds is odd in general, so I'm inclined to try the default bounds out and see what happens...

**Comment by AgustinVallejo** [comment]
Same as in https://github.com/phetsims/balancing-act/issues/109, removed the custom layoutBounds. Assigning back to review

**Comment by marlitas** [comment]
From Dev Meeting today it was decided that we would like to close all these issues as won't do. Before doing so we will need to revert the commits.

**Comment by pixelzoom** [comment]
Or for non-PhET-iO sims, something as simple as this in RAPConstants.ts:

```ts
  SCREEN_VIEW_LAYOUT_BOUNDS: new Bounds2( 0, 0, 835, 504 ), //TODO https://github.com/phetsims/reactants-products-and-leftovers/issues/75
```

**Comment by AgustinVallejo** [comment]
Changes reverted. Feel free to review and close @marlitas

**Comment by marlitas** [comment]
Sounds good let's close!
