### ISSUE TITLE
Add dynamic locale

### ISSUE THREAD

**Issue by marlitas** [phetsims/arithmetic#199]
THis issue will track work related to converting the sim to dynamic locale and it's usage of dynamic layout.

**Comment by marlitas** [comment]
Okay this issue is ready for review. Sending over to @Luisav1 or @AgustinVallejo. Whoever wants to get to it first.

One remaining TODO, that I need to check in with @pixelzoom about.

**Comment by AgustinVallejo** [comment]
Thanks for the insightful answer! Closing :)

**Comment by phet-dev** [comment]
Reopening because there is a TODO marked for this issue.

**Comment by marlitas** [comment]
Oops connected TODO to a different issue.
