### ISSUE TITLE
Replace NumberKeypad with Keypad

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/arithmetic#200]
Since work is being done on this sim... From https://github.com/phetsims/arithmetic/issues/7#issuecomment-1858370303:

> In our design discussion today, we also noted that arithmetic is using NumberKeypad, which is deprecated. It's the last sim to be using it, so it would be really great to convert to Keypad (the new solutions) so that we can delete NumberKeypad.

**Comment by marlitas** [comment]
This has been addressed in the above commit. Over to @Luisav1 or @AgustinVallejo for review.

**Comment by AgustinVallejo** [comment]
Looks like a clean fix to me! Closing

**Comment by pixelzoom** [comment]
I was hoping that NumberKeypad could now be deleted.  But I see that it's used in NumberEntryControl, which is used in area-builder and make-a-ten.
