### ISSUE TITLE
Optimize svg files with svgo

### ISSUE THREAD

**Issue by marlitas** [phetsims/arithmetic#201]
I experimented with a few of the Arithmetic svg files to see how much file size we can reduce by optimizing svg files with tools like [svgo](https://github.com/svg/svgo). 

It did successfully cut down the size of both the `svg` and corresponding `ts` files between 11-17% each, and I noticed no compromises to the quality of the svg when rendered in the sim. 

Results:
- 22.085 KiB - 16.8% = 18.37 KiB
- 15.693 KiB - 13.5% = 13.567 KiB
- 27.305 KiB - 11.8% = 24.092 KiB
- 21.242 KiB - 15.4% = 17.976 KiB

This savings will accumulate especially with sims that have a high number of svg files. I believe we should look into scaling this so that all svg files are run through an optimizer of some kind when added to sims.

Over to @jonathanolson and @kathy-phet for continued discussion.

**Comment by kathy-phet** [comment]
Thanks seems great! Tagging @amanda-phet so she is aware.

**Comment by jonathanolson** [comment]
Implemented the addition to chipper's modulify, so this will be run on all SVG images. Disabled the "remove viewbox" option, since we'll need that (for assorted reasons, and it's commonly disabled in other default lists - bounds and scaling issues).

@marlitas can you double-check things?

**Comment by pixelzoom** [comment]
PSA: This introduced a new dependency, and `cd chipper; npm update` is required.

**Comment by marlitas** [comment]
The changes look good. I double checked CT and see no errors. I also ran modulify on my machine and nothing suspicious happened. I will go ahead and paste this issue into the dev-public slack channel if any devs run into issues to report. Otherwise I believe this is ready to close. Thanks!
