### ISSUE TITLE
Missing dependency for timeText's PatternStringProperty

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/arithmetic#202]
In https://github.com/phetsims/axon/issues/441 `strictAxonDependencies` was turned on for all sims.

In ScoreBoardNode:

```ts
    const timeText = new Text( new PatternStringProperty( LABEL_TIME_STRING_PROPERTY, {
        time: currentElapsedTimeProperty
      },
      {
        formatNames: [ 'time' ],
        maps: {
          time: time => GameTimer.formatTime( time )
        }
      } ), TEXT_OPTIONS );
```

There are 2 StringProperties used by GameTimer.formatTimer that are not included in dependencies.  One way this could be resolved is by using DerivedStringProperty instead of PatternStringProperty.

In the meantime, https://github.com/phetsims/arithmetic/commit/3b8b9e4c3f324a58b1f97b452e9e75bff99e5115 adds `strictAxonDependencies: false` to this PatternStringProperty to opt out.

**Comment by pixelzoom** [comment]
The missing dependencies that appear in `GameTimer.formatTime` are:

* VegasStrings.pattern[ '0hours' ][ '1minutes' ][ '2secondsStringProperty' ]
* VegasStrings.pattern[ '0minutes' ][ '1secondsStringProperty' ]

**Comment by jbphet** [comment]
Fixed using the `DerivedStringProperty` approach suggested above.  Closing.
