### ISSUE TITLE
Add gameLevels query parameter

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/arithmetic#203]
As noted in https://github.com/phetsims/vegas/issues/122#issuecomment-1925417177, arithmetic is the last "game" sim that does not support `gameLevels`.  I was going to take care of it while adding support for `?gameLevels` to other sims.  But I discovered that all 3 screens are "games", each with a set of 3 level-selection buttons.   So I'm not sure how to proceed. 

Assigning to @amanda-phet, the responsible designer.

**Comment by pixelzoom** [comment]
In Slack#region-and-culture, @kathy-phet said:

> Re gameLevels for Arithmetic. Given the way the sim works, one reasonably simple option would be to stick with one query parameter, and have the behavior of gameLevels=1 is the smallest matrix, 2 next, and 3 next ... and it just applies to all the screens. So that you can get gameLevels=1,2 would remove the 12x12 on all the screens.
> 
> I'm fine with not doing it also, but if it's simple 30 minutes ...

**Comment by pixelzoom** [comment]
It would be < 30 minutes.  If @amanda-phet approves of that approach, assign the issue to me.

**Comment by pixelzoom** [comment]
Slack:

Amanda McGarry
That seems reasonable to me, and combined with 'screens' you could limit further.





Chris Malley
OK. I’ll proceed.


Kathy Perkins
:+1:

**Comment by pixelzoom** [comment]
Done, ready for @amanda-phet to review.

**Comment by amanda-phet** [comment]
This is working well.
