### ISSUE TITLE
USA artwork has see through lines

### ISSUE THREAD

**Issue by marlitas** [phetsims/arithmetic#204]
While working on Arithmetic @Luisav1  and I noticed that the artwork for the USA characters had some see through bits:

<img width="324" alt="image" src="https://github.com/phetsims/arithmetic/assets/42476338/6972f08c-b851-42cd-8247-fd0f4addc0b4">

We felt this might be similar to this issue from balancing act: https://github.com/phetsims/balancing-act/issues/147
@amanda-phet we might need to re-export that artwork and maybe do some adjustments to the svg.

**Comment by amanda-phet** [comment]
Waiting on new artwork from @mariahmaephet and then I will update the USA characters for the Multiplication levels.

**Comment by amanda-phet** [comment]
Over to @Luisav1 to incorporate the new artwork! We should also update the license to say Mariah is the artist.

**Comment by Luisav1** [comment]
The new artwork is integrated in the above commit and it's looking good to me!
![image](https://github.com/phetsims/arithmetic/assets/52978048/f08f920f-e43b-4544-81d0-91767a613c52)

@amanda-phet Could you please review to ensure it's good before closing? Thanks!

**Comment by amanda-phet** [comment]
They look great to me!
