### ISSUE TITLE
Increase level-selection button size to show off artwork 

### ISSUE THREAD

**Issue by Luisav1** [phetsims/arithmetic#205]
See https://github.com/phetsims/graphing-lines/issues/145.

**Comment by Luisav1** [comment]
Increased button size above to showcase artwork.
Before:
![image](https://github.com/phetsims/arithmetic/assets/52978048/9f128fb9-7ebf-4101-9873-a0d0525a95dc)
Now:
![image](https://github.com/phetsims/arithmetic/assets/52978048/18ce2253-b570-46f1-a770-7c252743f8cd)
![image](https://github.com/phetsims/arithmetic/assets/52978048/fd8af5fd-5964-42d1-b95c-4d1979c5d2dd)

Assigning @amanda-phet to review before closing.

**Comment by amanda-phet** [comment]
Reviewed on phettest. These look great to me!
