### ISSUE TITLE
Block outline color is incorrect 

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/arithmetic#209]
For https://github.com/phetsims/qa/issues/1046, on the Divide Screen the block outline color is black instead of white for the third scene using the Africa character set.

I don't see this with any of the other character sets. 

<img width="838" alt="Screenshot 2024-02-23 at 12 52 38 PM" src="https://github.com/phetsims/arithmetic/assets/87318828/74b194c6-276e-4b5b-a90e-7d5c63fdd7e9">

**Comment by amanda-phet** [comment]
Ughhhh I'm not sure how that happened. I will work on replacing this.

**Comment by amanda-phet** [comment]
I uploaded a new icon for this.

**Comment by Luisav1** [comment]
Thanks @amanda-phet. The new image is looking good to me!
![image](https://github.com/phetsims/arithmetic/assets/52978048/35bb0bf0-b970-4c81-ba41-bf3cc7eb3638)
