### ISSUE TITLE
Should the '?' disappear after the first entry?

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/arithmetic#210]
**Test device**
MacBook Air M1 chip

**Operating System**
14.3.1

**Browser**
Safari 17.3.1

**Problem description**
For https://github.com/phetsims/qa/issues/1046 and related to https://github.com/phetsims/arithmetic/issues/7, on the Multiply Screen, there is a question mark in the answer box for each new problem. On the Divide screen, the question mark goes away after the first question is answered. I'm not sure which behavior was the desired one here (personally, I like that the question mark goes away after the first question is answered). 
Also noting that pressing the Eraser button causes the question mark to reappear on the Divide screen. 

**Visuals**

https://github.com/phetsims/arithmetic/assets/87318828/0cc67504-eaad-4272-a582-cb96538d0e2a

**Comment by Luisav1** [comment]
@amanda-phet Could you weigh in on this? I'm not sure what the desired behaviour would be here either.

**Comment by amanda-phet** [comment]
I reviewed #7 and it seems like the suggestions for a question mark was only for the case where we didn't end up adding keyboard input. 

Before I suggest removing the question mark- Do either of you know why we added it when we added keyboard input?

**Comment by amanda-phet** [comment]
@marlitas do you remember why the question mark was added?

**Comment by amanda-phet** [comment]
@marlitas @Luisav1 and I tried to do some digging around and can't figure out why this '?' showed up between December and February. 

We do need the '?' on the Factor screen, for the two unknowns, because that screen doesn't have keyboard or keypad input. 

We would like to remove the '?' from the Multiply and Divide screens.

**Comment by Luisav1** [comment]
We may have  this was added in https://github.com/phetsims/arithmetic/commit/e4db552f18b2f9be3ffa0660920e6273caf6799e so I removed the code that made it visible in `clear()` in `EquationInputNode`.

I also made the '?' invisible by default so it isn't visible at the start of the games either.

Now the '?' only appears in the factor screen.

@Nancy-Salpepi Could you review this as well to ensure it's what you expect?

**Comment by Nancy-Salpepi** [comment]
Things look good on the Multiply screen. 
The '?' still appears every time the Eraser button is pressed in a game level on the Divide Screen.

Steps:
1. Enter any game level on the Divide Screen
2. Press the eraser button--The question mark will appear
3. Press Start Over button and enter a different game level --the question mark will be there too

**Comment by Luisav1** [comment]
Ah oops, thanks @Nancy-Salpepi. This is ready for review again. I believe both the Multiply and Divide screen should now be following this behaviour.

**Comment by Nancy-Salpepi** [comment]
This looks good now @Luisav1! Closing.
