### ISSUE TITLE
Hand silhouette doesn't reappear with Reset All

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/arithmetic#211]
**Test device**
MacBook Air M1 chip

**Operating System**
14.3.1

**Browser**
Safari 17.3.1

**Problem description**
For https://github.com/phetsims/qa/issues/1046, the large cueing hand silhouette doesn't reappear in a game level after Reset All is pressed on the Factor Screen. 
This issue also appears in the published version of the sim.

**Steps to reproduce**
1. Enter a game level on the Factor Screen
2. Select a cell and then exit out
3. Press the Reset All button
4. Reenter the game level or a different one

**Visuals**

https://github.com/phetsims/arithmetic/assets/87318828/a9a1088e-78c4-4805-b078-1a1f65932e4c

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Arithmetic‬
URL: https://phet-dev.colorado.edu/html/arithmetic/1.1.0-dev.4/phet/arithmetic_all_phet.html
Version: 1.1.0-dev.4 2024-02-21 16:48:20 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
Language: en-US
Window: 1384x728
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by Luisav1** [comment]
This is fixed in the commit above by adding a `handImageVisibleProperty` that is reset whenever the level is reset.

https://github.com/phetsims/arithmetic/assets/52978048/75d994ed-8bd0-46ea-9c9b-318fcf2395e4

Closing.
