### ISSUE TITLE
Unable to build an RC

### ISSUE THREAD

**Issue by jbphet** [phetsims/arithmetic#213]
@Luisav1 was running into problems building an RC for this sim and asked me to take a look with her.  After some investigation, we found the the problem was occurring on the build server.  Here is an excerpt from the build server log that shows the error:

```
Mar 12 10:14:19 phet-server2.int.colorado.edu build-server[2559485]: info: queuing build for arithmetic 1.1.0-rc.1
Mar 12 10:14:19 phet-server2.int.colorado.edu build-server[2559485]: info: Validating repo: comment
Mar 12 10:14:19 phet-server2.int.colorado.edu build-server[2559485]: info: Validating repo: arithmetic
Mar 12 10:14:19 phet-server2.int.colorado.edu build-server[2559485]: info: Validating repo: assert
Mar 12 10:14:19 phet-server2.int.colorado.edu build-server[2559485]: info: Validating repo: axon
Mar 12 10:14:19 phet-server2.int.colorado.edu build-server[2559485]: info: Validating repo: brand
Mar 12 10:14:19 phet-server2.int.colorado.edu build-server[2559485]: info: Validating repo: chipper
Mar 12 10:14:19 phet-server2.int.colorado.edu build-server[2559485]: info: Validating repo: dot
Mar 12 10:14:19 phet-server2.int.colorado.edu build-server[2559485]: info: Validating repo: joist
Mar 12 10:14:19 phet-server2.int.colorado.edu build-server[2559485]: info: Validating repo: kite
Mar 12 10:14:19 phet-server2.int.colorado.edu build-server[2559485]: info: Validating repo: perennial-alias
Mar 12 10:14:19 phet-server2.int.colorado.edu build-server[2559485]: info: Validating repo: phet-core
Mar 12 10:14:19 phet-server2.int.colorado.edu build-server[2559485]: info: Validating repo: phet-io
Mar 12 10:14:19 phet-server2.int.colorado.edu build-server[2559485]: info: Validating repo: phet-io-sim-specific
Mar 12 10:14:19 phet-server2.int.colorado.edu build-server[2559485]: info: Validating repo: phet-io-sim-specific/repos/arithmetic/wrappers/check-answers
Mar 12 10:14:19 phet-server2.int.colorado.edu build-server[2559485]: error: BUILD ABORTED! invalid simName in dependencies: arithmetic
Mar 12 10:14:19 phet-server2.int.colorado.edu build-server[2559485]: error: BUILD ABORTED! Error: Build aborted, invalid simName in dependencies: arithmetic
Mar 12 10:14:19 phet-server2.int.colorado.edu build-server[2559485]: error: Error: Build aborted, invalid simName in dependencies: arithmetic
Mar 12 10:14:19 phet-server2.int.colorado.edu build-server[2559485]:     at abortBuild (/data/share/phet/build-server/perennial/js/build-server/taskWorker.js:29:9)
Mar 12 10:14:19 phet-server2.int.colorado.edu build-server[2559485]:     at runTask (/data/share/phet/build-server/perennial/js/build-server/taskWorker.js:110:17)
Mar 12 10:14:19 phet-server2.int.colorado.edu build-server[2559485]:     at taskWorker (/data/share/phet/build-server/perennial/js/build-server/taskWorker.js:354:3)
Mar 12 10:14:19 phet-server2.int.colorado.edu build-server[2559485]:     at Immediate.process (/data/share/phet/build-server/perennial/node_modules/async/lib/async.js:806:21)
Mar 12 10:14:19 phet-server2.int.colorado.edu build-server[2559485]:     at processImmediate (node:internal/timers:466:21)
```

I searched through the build-server code in the perennial repo for the error message and found it in `taskWorker.js`, currently at line 111.  The code is just checking whether the repo name is made up of lower case letters and hyphens, and it's failing on a dependency that the arithmetic sim has that is `phet-io-sim-specific/repos/arithmetic/wrappers/check-answers`.  This is definitely in the `dependencies.json` file on main, and appears to have been added when @Luisav1 created a dev version, see https://github.com/phetsims/arithmetic/commit/3c35f18da1176eb1f0ffd0a7ca8a20cbd1340cf8.  But why would creating a dev version add a dependency that makes the sim unbuildable?

To find an answer to this question, @Luisav1 has set up a meeting to discuss why this dependency has changed like this and what we should do about it.  We will update this issue with the results.

**Comment by zepumph** [comment]
This was broken because of my work in https://github.com/phetsims/phet-io-wrappers/issues/636. @jbphet @Luisav1 @mattpen and I were all surprised that we were able to get so downstream in the process before a dependency called `phet-io-sim-specific/repos/arithmetic/wrappers/check-answers` errored out. I will do two things to remedy:

1. getDependencies should use the same regex in taskWorker (that failed the build) to double check that dependencies are valid simNames.
2. getPhetLibs should update its' phet-io wrappers section to handle this better.

**Comment by zepumph** [comment]
The only potential sims effected by this are:

```
arithmetic
circuit-construction-kit-dc
my-solar-system
projectile-data-lab
projectile-motion
```

And I don't believe any others have had an RC created since january, so I don't think any other sims need help than arithmetic.

**Comment by zepumph** [comment]
Alright. Commits are above. Next steps:

1. @Luisav1 please cherry pick https://github.com/phetsims/chipper/commit/e4dc9cab5319a0fbac8277df396d92529693d354 to your rc branch for arithmetic.
2. Please manually edit the top level dependencies.json in your release branch so that it doesn't have this extra `phet-io-sim-specific/...` path in it.

Sorry for the trouble.

**Comment by Luisav1** [comment]
No worries, thanks @zepumph! The RC was able to build successfully. Closing.
