### ISSUE TITLE
Convert to new approach for Region and Culture

### ISSUE THREAD

**Issue by Luisav1** [phetsims/arithmetic#215]
For https://github.com/phetsims/joist/issues/958.

The changes were done in https://github.com/phetsims/arithmetic/commit/970fe8bea109c48197d4b409747599138393ce1c.

@amanda-phet This needs a design review to ensure the Region and Culture changes were alright. The changes can be seen in main.

**Comment by amanda-phet** [comment]
The preferences dialog looks how I would expect. 

Can we make `random` the default selection for Region & Culture?

**Comment by Luisav1** [comment]
Although the default in general for R&C is `usa` (from https://github.com/phetsims/joist/issues/957#issue-2174982628), @amanda-phet confirmed with @kathy-phet that we'll use `random` as the default when the `usa` set is only one character, such as this sim.

**Comment by Luisav1** [comment]
Closing since this has been reviewed and #214 set the default to `random`.
