### ISSUE TITLE
Should the "Invalid Query Parameters" dialog appear?

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/arithmetic#216]
**Test device**
MacBook Air M1 chip

**Operating System**
14.3.1

**Browser**
Safari 17.3.1

**Problem description**
For https://github.com/phetsims/qa/issues/1057, when using an invalid option for ?regionAndCulture, the sim fails to load and there is an error in the console. This is different behavior than in the Number Line Suite where the Invalid Query Parameters dialog appears. I was wondering what determines whether the invalid QP dialog pops up? 
@pixelzoom perhaps you know the answer to this?

**Steps to reproduce**
1. Add ?regionAndCulture=birds (or any other word) to the end of the url

**Visuals**
<img width="1344" alt="Screenshot 2024-03-15 at 2 14 10 PM" src="https://github.com/phetsims/arithmetic/assets/87318828/5c6eb7aa-19b5-431b-899a-9054763a8817">
<img width="965" alt="Screenshot 2024-03-15 at 2 10 03 PM" src="https://github.com/phetsims/arithmetic/assets/87318828/c81e8d1e-4311-417b-aa0f-9390f92eeb7e">

**Comment by Nancy-Salpepi** [comment]
From Slack:
Chris Malley
It looks like the regionAndCulture query parameter schema in initialize-globals.ts is missing the validValues field.  So the query parameter parser assumes that all values are valid, and it fails further downstream.  Fix coming up…

Nancy Salpepi
thanks!

Chris Malley
Fix pushed.  Note that regionAndCulture=usa is always valid, regardless of whether the sim has a Region and Culture combo box.

A non ‘usa’ value must be one of the values supported by the sim. For example, regionAndCulture=oceania will fail for CAV, because it’s not a region support by that sim. Something like regionAndCulture=foo will fail for all sims.

**Comment by Nancy-Salpepi** [comment]
This looks good on main!
Closing!

**Comment by Nancy-Salpepi** [comment]
Actually, I am going to reopen this. I am not sure how @Luisav1 is creating the new rc branch and I want to make sure the changes that were made in https://github.com/phetsims/chipper/issues/1422 make it into the branch.

**Comment by pixelzoom** [comment]
@Luisav1 if you need to cherry pick this, the sha is https://github.com/phetsims/chipper/commit/c1663259f4134d9119e117a05d960b56fb142bd4.

**Comment by Luisav1** [comment]
Thanks @Nancy-Salpepi and @pixelzoom. I don't believe I'll need to cherry-pick it since the 1.1 branch was deleted so when I create the new RC it should take the correct chipper SHA, if my understanding is correct.

**Comment by pixelzoom** [comment]
You have the right @Luisav1.  If you have not created the new 1.1 branch yet, then you'll pick up the change from master when you do so.
