### ISSUE TITLE
Unable to select square on factor screen

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/arithmetic#217]
**Test device**
MacBook Air M1 chip

**Operating System**
14.3.1

**Browser**
Safari 17.3.1

**Problem description**
For https://github.com/phetsims/qa/issues/1057 I am no longer able to select a square to submit an answer on the Factor screen.

**Steps to reproduce**
1. On an game level in the Factor screen try to select a square 

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Arithmetic‬
URL: https://phet-dev.colorado.edu/html/arithmetic/1.1.0-dev.5/phet/arithmetic_all_phet.html
Version: 1.1.0-dev.5 2024-03-15 16:50:33 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
Language: en-US
Window: 1152x584
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by Luisav1** [comment]
Ah whoops, missed testing this, since there is an invisible rectangle now overlaying on top of the cell (added in #208), when zoomed in, it is covering the cell. I will look into solutions to this.

**Comment by Luisav1** [comment]
The `panToNodeRectangle` that was overlayed on top of the cell was removed in https://github.com/phetsims/arithmetic/commit/0ba3c5fd65c28e27779bcd27d169cb3cb61fa90a for #208. So the squares can now be selected again. Closing.
