### ISSUE TITLE
Possible to submit no answer with Enter key

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/arithmetic#223]
**Test device**
MacBook Air M1 chip + Chromebook

**Operating System**
14.4.1

**Browser**
Safari + Chrome

**Problem description**
For https://github.com/phetsims/qa/issues/1056, after entering an incorrect answer, it is possible to submit no answer using the Enter key.  A "0" will appear in the answer box and the user is told they have an incorrect answer. It isn't possible to submit no answer initially (before an incorrect guess). 

**Steps to reproduce**
1. On any level on Screens 1 or 3, enter an incorrect answer
2. Press the Try Again button using mouse or by pressing Enter key
3. Press Enter key

**Visuals**

https://github.com/phetsims/arithmetic/assets/87318828/81d24547-b0b4-4bbb-b028-32d75f1d93d9

**Comment by Luisav1** [comment]
The issue was that when an incorrect answer was entered, the keypad kept that incorrect answer around as an accumulated key so now the keypad is cleared when there's an incorrect answer. Keeping this open to verify in the next RC.

**Comment by Luisav1** [comment]
This has been cherry-picked into Arithmetic 1.2 and is ready for review by QA.

**Comment by Nancy-Salpepi** [comment]
Working nicely in 1.2.0-rc.2.
Closing!
