### ISSUE TITLE
Color changes

### ISSUE THREAD

**Issue by jbphet** [phetsims/arithmetic#31]
In a review meeting on 6/13/2014, several color changes were recommended by the original designer of the sim and the current redesign lead.  This ticket is meant to track these changes.

- The scoreboard color should be lightened so that there is more contrast with the textual labels.
- The background of the level selection screen should be a blue color, perhaps the color of the scoreboard.
- The 'Refresh' and 'ReturnToLevelSelection' buttons are fairly orange, and they are more yellow in other sims.  The color should be moved towards yellow.

**Comment by jbphet** [comment]
This sim is on hold for a while, so I'm unassigning this issue until work resumes.

**Comment by jbphet** [comment]
Assigning to @amanda-phet to determine what, if any, additional color changes should be made.

**Comment by amanda-phet** [comment]
Please make the score panel a light gray. I'd go ahead and use the gray that is being used in the number boxes. 

Also, the buttons should be adjusted to be the default yellow that is in other sims (the yellow that is on the Continue button when completing a level). 

![screen shot 2015-11-11 at 4 02 31 pm](https://cloud.githubusercontent.com/assets/7852916/11105684/c2824c94-888d-11e5-84dc-f893c0e88f6f.png)

**Comment by jbphet** [comment]
The control panel color change has been implemented.  I discussed the changes to the button colors with @amanda-phet and we decided to leave them as the current orangeish color for now since we vaguely recall discussing colors quite a bit when this sim with in development last year, and because the other sims have a lot of variation in the color of these buttons so there isn't really a standard.

**Comment by jbphet** [comment]
Upon further review, the ruling on the field is overturned, and we're going with yellow buttons.  I tried it out, and the just look better to both my and @amanda-phet's eye.  I've reviewed these changes with @amanda-phet, so the work for this issue is now complete.  Closing.
