### ISSUE TITLE
Finalize credits for v1.0

### ISSUE THREAD

**Issue by jbphet** [phetsims/arithmetic#95]
The credits are looking reasonably good, but the QA team should be added before publication.

**Comment by jbphet** [comment]
This sim is on hold for a while, so I'm unassigning this issue until work resumes.

**Comment by jbphet** [comment]
Assigning to @ariel-phet to review and make sure that these appear correct on v1.0.0-rc.1.  

Link: http://www.colorado.edu/physics/phet/dev/html/arithmetic/1.0.0-rc.1/arithmetic_en.html

**Comment by ariel-phet** [comment]
Please add Amanda to the credits as lead design, and move Bryce from lead design to just the design team

**Comment by jbphet** [comment]
Assigning to @ariel-phet for (hopefully) final verification on v1.0.0-rc.2, available here: http://www.colorado.edu/physics/phet/dev/html/arithmetic/1.0.0-rc.2/arithmetic_en.html.

**Comment by ariel-phet** [comment]
Looks good, closing
